# Keep PATH/fpath entries unique; zshrc re-sources this file, so without
# this every re-source duplicates entries (mise shims, ~/bin, etc.)
typeset -U path fpath

# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";

## https://esham.io/2018/02/zsh-profiling
# zmodload zsh/datetime
# setopt PROMPT_SUBST
# PS4='+$EPOCHREALTIME %N:%i> '
# logfile=$(mktemp zsh_profile.XXXXXXXX)
# echo "Logging to $logfile"
# exec 3>&2 2>$logfile
# setopt XTRACE

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# Secrets are split per environment: staging is the ambient default here;
# prod.secrets is sourced only inside `envbox prod`.
for file in ~/.{aliases,functions,exports,extra,fzf.zsh,nurc,cargo/env,frontierrc,staging.secrets} /usr/share/doc/fzf/examples/key-bindings.zsh; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# unsetopt XTRACE
# exec 2>&3 3>&-
# /tmp/sortt.sh $HOME/$logfile
